language: python
python: 2.7
branches:
  only:
  - master

install: pip install mkdocs
script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git remote remove origin
- git remote add origin https://${GH_TOKEN}:@github.com/sweady/sweady.git
- cd docs
- mkdocs gh-deploy --force