language: python
python: 2.7
branches:
  only:
  - master

script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git subtree push -P docs https://${GH_TOKEN}:@github.com/Sweady/docs.git  master
- git subtree push -P cli  https://${GH_TOKEN}:@github.com/Sweady/cli.git   master