version: '3'

volumes:
  prometheus_config:
    driver_opts:
      device: '/mnt/data/monitoring/prometheus/config'
      type: none
      o: bind
  prometheus_data:
    driver_opts:
      device: '/mnt/data/monitoring/prometheus/data'
      type: none
      o: bind
  grafana_data:
    driver_opts:
      device: '/mnt/data/monitoring/grafana/data'
      type: none
      o: bind
  mongo_data:
    driver_opts:
      device: '/mnt/data/monitoring/mongo/data'
      type: none
      o: bind
  elastic_data:
    driver_opts:
      device: '/mnt/data/monitoring/elastic/data'
      type: none
      o: bind
  elastic_config:
    driver_opts:
      device: '/mnt/data/monitoring/elastic/config'
      type: none
      o: bind
  graylog_data:
    driver_opts:
      device: '/mnt/data/monitoring/graylog/data'
      type: none
      o: bind
  graylog_config:
    driver_opts:
      device: '/mnt/data/monitoring/graylog/config'
      type: none
      o: bind

networks:
  monitoring:
    driver: overlay

services:
  mongo:
    image: mongo:3
    deploy:
      placement:
        constraints:
          - node.role == worker
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: elasticsearch:2-alpine
    deploy:
      placement:
        constraints:
          - node.role == worker
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
      - elastic_config:/usr/share/elasticsearch/config
    command: "elasticsearch -Des.cluster.name='graylog'"

  graylog:
    image: graylog2/server
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - graylog_data:/usr/share/graylog/data/journal
      - graylog_config:/usr/share/graylog/data/config
    environment:
      - GRAYLOG_PASSWORD_SECRET=cH5mQ7ANxhh4555T
      - GRAYLOG_ROOT_PASSWORD_SHA2=031da2e44853d568de256e09e77388ce0e4474a79e7abf3303222aeaec8b7f21
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "1514:1514/udp"



  prometheus:
    image: prom/prometheus
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - prometheus_config:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-storage.local.retention=48h'
    depends_on:
      - cadvisor
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    deploy:
      placement:
        constraints:
          - node.role == manager
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  node-exporter:
    image: prom/node-exporter
    deploy:
      mode: global
    networks:
      - monitoring

  cadvisor:
    image: google/cadvisor
    deploy:
      mode: global
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring