---
    - name: Ensure GlusterFS is installed.
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - glusterfs-client
      when: "inventory_hostname == groups.swarm_manager or inventory_hostname == groups.swarm_worker"

    - name: Ensure the Gluster volume is mounted.
      mount:
        name: "{{ gluster_mount_dir }}"
        src: "{{ groups.swarm_glusterfs[0] }}:/{{ gluster_brick_name }}"
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted
      when: "inventory_hostname == groups.swarm_manager or inventory_hostname == groups.swarm_worker"