---
# Deps for ansible
- hosts: localhost
  tasks:
    - name: "run ansible galaxy"
      local_action: command ansible-galaxy install -r ../requirements.yml

# Init & full update
- hosts: all
  become: true
  become_user: root
  pre_tasks:
    - include: base/pre_tasks.yaml
  roles:
    - GoContainer.system-update

# Base
- hosts: swarm_glusterfs
  become: true
  become_user: root
  vars:
    glusterfs_ppa_use: false
    disk_additional_disks:
      - disk: /dev/{{ disk }}
        fstype: ext4
        mount_options: defaults
        mount: /data
    gluster_mount_dir: /var/lib/docker/volumes
    gluster_brick_dir: /data
    gluster_brick_name: gluster
  roles:
    - AerisCloud.disk
    - GoContainer.glusterfs
  tasks:
    - include: base/glusterfs.ansible.yaml

- hosts: swarm_master:swarm_node
  become: true
  become_user: root
  roles:
    - GoContainer.docker-local-persist
  tasks:
    - include: base/install_docker.yaml

# Create
- hosts: all
  become: true
  become_user: root
  vars:
    glusterfs_ppa_use: false
    gluster_mount_dir: /var/lib/docker/volumes
    gluster_brick_dir: /data
    gluster_brick_name: gluster

  tasks:
    - include: create/glusterfs_mount.ansible.yaml
    - include: create/swarm_cluster.ansible.yaml
    - include: create/install_sweady.ansible.yaml
