---
- hosts: all
  user: root
  become: true
  vars:
    gluster_mount_dir: /mnt/data
    gluster_brick_name: gluster

  pre_tasks:
    - name: Clear file
      command: rm -rf /etc/apt/apt.conf.d/50unattended-upgrades*

  roles:
    - GoContainer.system-update
    - GoContainer.docker-local-persist
